[package]
name = "rust-guessing-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5" #run cargo build when dependency is added
colored = "2.0.0"